num_file1: ""          # пусто = генерировать
num_file2: ""          # пусто = генерировать
num_size: 128          # количество элементов []int64 (~1кб)
pow: 9                 # сколько цифр хранится в каждом элементе
out_dir: "bin/out"     # папка для вывода
