num_file1: ""          # пусто = генерировать или вставь in/num1.txt
num_file2: ""          # пусто = генерировать или вставь in/num2.txt
num_size: 10000          # количество элементов []int64 (~1кб)
pow: 3               # взять степень на число какое
out_dir: "bin/out"     # папка для вывода
